import './globals.css'
import { Inter, Urbanist } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],  
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>{children}</body>
    </html>
  )
}
